/* =====================================================================
   TOEFL Writing 添削講座 — Academic Discussion 問題データ（全12セット）
   Set 1–8 : 既存（クライアント提供PDFより）
   Set 9–12: 新規作成（教授60–80語 / 学生40–60語・語数検証済み）
   フィールド:
     field   = 学問分野（"Your professor is teaching a class on ___." に入る）
     qType   = 'Alternative' | 'Free-response'
     prof    = 教授の表示名
     profPost= 教授の投稿本文（最後は質問で締める）
     s1/s2   = 学生名 / s1Post,s2Post = 学生の投稿本文（異なる立場）
   ===================================================================== */
const AD_SETS = [
  { set:1, field:"genetics", qType:"Alternative", prof:"Professor",
    profPost:"Welcome to today's discussion on the ethics of genetic engineering. Genetic manipulation can offer medical advancements and improved quality of life, but it also raises concerns about playing with nature and unforeseen consequences. The line between healing and overreaching is still very unclear. If you had to decide whether to support the expansion of genetic engineering or ban it, which would you choose, and why?",
    s1:"Oliver", s1Post:"I would support the expansion of genetic engineering for medical purposes. The potential to cure genetic diseases and alleviate suffering is immense. Advancements in medicine often involve pushing boundaries. Responsible research, transparent communication, and stringent oversight can ensure that genetic engineering benefits society without disregarding ethical values.",
    s2:"Ava", s2Post:"I lean towards banning genetic engineering due to ethical concerns. Manipulating genetics raises moral dilemmas about tampering with the fundamental aspects of life. Unintended consequences could lead to unforeseen problems. While medical advancements are important, we should proceed cautiously and prioritize the sanctity of nature and the preservation of the essence of being human." },

  { set:2, field:"leadership skills", qType:"Free-response", prof:"Professor",
    profPost:"When individuals are asked about the most vital abilities necessary for effective leadership in today's world, they often mention those immediately apparent, like communication or charisma. However, numerous other skills are equally indispensable and shape how we become successful leaders. These less obvious abilities often separate the leaders who succeed long-term from those who do not. Which specific leadership skill would you consider important for effective leadership today? Why?",
    s1:"Mia", s1Post:"In my view, \"decision-making under uncertainty\" is a critical leadership skill. Leaders often face situations with incomplete information and rapidly changing variables. The ability to make well-informed decisions despite uncertainty is essential. It involves risk assessment, adaptability, and the courage to take calculated risks. Leaders who excel in it can steer their teams through ambiguity toward lasting success.",
    s2:"Alex", s2Post:"Adaptability is my chosen skill for effective leadership today. With constant changes in markets, technologies, and customer expectations, leaders must be agile and open to change. An adaptable leader can quickly assess new situations, make informed decisions, and guide their team through transitions. This skill ensures organizational resilience and empowers teams to thrive in dynamic environments." },

  { set:3, field:"media", qType:"Alternative", prof:"Professor",
    profPost:"Our topic for today's discussion is advertising and its multifaceted impacts on modern society. Advocates assert that advertising is a cornerstone of the economy, driving consumer demand and fostering competition. Others argue that advertising often perpetuates harmful stereotypes and invades personal privacy. These tensions often appear together in our daily exposure to ads, making the issue difficult to settle. What's your stance on this issue? Do you believe advertising is more beneficial or harmful?",
    s1:"Natalie", s1Post:"In my opinion, advertising is a complex phenomenon with both positive and negative aspects. On the positive side, it facilitates healthy competition among businesses, leading to innovation and improved products. There are undeniable negative effects, but I think we as consumers can make a conscious effort to be aware of these effects.",
    s2:"Owen", s2Post:"I disagree with Natalie's perspective. The invasion of personal privacy through targeted ads raises ethical concerns. As a solution, implementing stricter regulations on data collection and usage for advertising purposes is crucial to safeguard individual privacy. Advertisers should also take a more proactive role in promoting socially responsible behavior and sustainability, shifting away from purely profit-driven motives." },

  { set:4, field:"sociology", qType:"Alternative", prof:"Professor Rodriguez",
    profPost:"Welcome to today's classroom discussion on the topic of surveillance. In an era where computers track the websites we visit and surveillance cameras observe us in many public places, the debate over the balance between security and privacy continues to gain prominence. Many people argue these systems make us safer, while others see them as a slow loss of personal freedom we cannot recover. Do you think that this kind of monitoring is justifiable?",
    s1:"Isabella", s1Post:"I believe that surveillance is justifiable. In an age of increased security threats, such as cyberattacks and terrorism, surveillance measures can help protect society. For instance, tracking online activities can help detect potential threats or investigate online frauds. With a clear legal framework and transparency, we can avoid any privacy issues.",
    s2:"Ethan", s2Post:"I think surveillance infringes upon our right to privacy. The constant monitoring of our online activities and movements erodes the personal freedom and autonomy that should be cherished in any democratic society. Some surveillance is justifiable for security, but the current extent has gone too far and needs stricter oversight to protect our civil liberties." },

  { set:5, field:"urban planning", qType:"Alternative", prof:"Professor",
    profPost:"Our exploration of urban planning has highlighted the tension between preserving historical architecture and promoting modern development. Some argue that preserving historic buildings maintains cultural identity and a sense of place. Others believe that embracing contemporary architecture signals progress and innovation. Should urban planning prioritize the preservation of historical architecture or the integration of modern designs to shape the urban landscape?",
    s1:"Oliver", s1Post:"I believe that urban planning should try to preserve historical architecture as it reflects the identity and heritage of a community. At the same time, incorporating modern designs can enhance the vitality of urban areas and respond to evolving needs. Effective urban planning recognizes the value of both, ensuring that cities evolve while maintaining a connection to their past.",
    s2:"Ava", s2Post:"I lean towards the importance of modern designs in urban planning. Embracing contemporary architecture allows cities to adapt to changing social and technological landscapes. While historical preservation is vital, it's equally crucial to create spaces that reflect the needs and aspirations of current and future generations." },

  { set:6, field:"sociology", qType:"Alternative", prof:"Prof. Lewis",
    profPost:"As I mentioned in class, teenagers having part-time jobs during their school years is a common practice in many societies. Part-time work allows teens to learn valuable life skills, but balancing work and academics can become difficult. In some families, the extra income also helps cover expenses, which makes the decision even more complicated. Do you think teenagers should have part-time jobs while they are still students? Why or why not?",
    s1:"Hannah", s1Post:"I believe teenagers should have part-time jobs because these jobs instill financial responsibility. By experiencing working life, students are better able to understand the value of money once they have worked hard to earn a wage. Part-time work also teaches time management and confidence, skills that classrooms alone cannot easily provide.",
    s2:"Chris", s2Post:"I disagree with the idea of teenagers having part-time jobs while they're still students. School demands are already quite heavy, and adding a job to the mix can lead to academic struggles. Teenagers need time to focus on their studies and personal growth without the added stress of work." },

  { set:7, field:"consumer behavior", qType:"Alternative", prof:"Prof. Davis",
    profPost:"In consumer behavior, we often assume that consumers always seek the lowest prices when shopping for particular products. However, real-world shopping decisions are influenced by a multitude of factors. Brand image, perceived quality, peer recommendation, and even environmental concerns can all overshadow price in a given decision. Do you agree or disagree with the following statement? \"The lower the price of a product, the more likely people will buy the product.\"",
    s1:"Emma", s1Post:"I disagree with the statement. While price is undoubtedly a significant factor, it is not the sole driver of purchasing decisions. Quality and brand reputation can sway people's choices. For instance, if a trusted brand offers a slightly higher-priced product known for durability and reliability, I would opt for it over a cheaper, unfamiliar option.",
    s2:"Daniel", s2Post:"I agree with the statement to a large extent. In many cases, lower prices do attract more buyers, especially for everyday items and commodities such as groceries. Due to the current economic state, I think more people are conscious about the price, and opt for budget-friendly options to manage their household expenses." },

  { set:8, field:"corporate responsibility", qType:"Alternative", prof:"Prof. Anderson",
    profPost:"Recently, major tobacco companies agreed to pay a financial settlement to several states, for health problems caused by cigarette smoking. In the context of corporate responsibility, we often encounter debates about whether companies should be held accountable for accidents or harm that result from the misuse of their products. Should companies be held responsible for any accidents or harm that result from their products?",
    s1:"David", s1Post:"I agree that companies should be held accountable for their products. They have a moral obligation to prioritize the safety and well-being of their customers. When a company designs and sells a product, it assumes responsibility for its safety and performance, and that responsibility extends beyond the point of purchase to the entire product lifecycle.",
    s2:"Sophie", s2Post:"I disagree. Placing the entire responsibility on companies is not only unfair but also hinders innovation. Companies should certainly prioritize safety and provide clear guidelines for product use, but ultimately, individuals should be responsible for their actions. Holding companies accountable for accidents due to misuse sets a troubling precedent and discourages them from developing innovative products." },

  /* ---------- 新規作成（Set 9–12） ---------- */
  { set:9, field:"environmental science", qType:"Alternative", prof:"Dr. Hayashi",
    profPost:"As we have seen this semester, reducing environmental damage requires action at many levels. Some argue that meaningful change depends mainly on individuals adjusting their daily habits, such as cutting waste and saving energy. Others insist that only government regulation of large industries can produce real impact. Which approach do you think matters more for protecting the environment, and why?",
    s1:"Lena", s1Post:"I think individual choices matter most. When millions of people reduce waste, save energy, and choose sustainable products, the combined effect is enormous. Personal habits also shape demand, which pushes companies to change. If consumers stop buying wasteful products, businesses gain a strong reason to produce greener alternatives.",
    s2:"Tomás", s2Post:"I disagree with Lena. Individual efforts are helpful, but they are too small and inconsistent to solve large problems. Most pollution comes from a handful of big industries. Without strict government regulations and real penalties, these companies have little incentive to change, no matter how careful ordinary people try to be." },

  { set:10, field:"education", qType:"Alternative", prof:"Dr. Okonkwo",
    profPost:"Many universities require students to take a range of courses outside their main field, such as art, history, or science, regardless of their major. Supporters say this broadens students' thinking and prepares them for a changing world. Critics argue that it wastes time and money better spent gaining depth in a chosen field. Should universities require these courses? Why or why not?",
    s1:"Priya", s1Post:"I believe these requirements are valuable. Exploring subjects outside your major builds flexible thinking and exposes you to ideas you would never encounter otherwise. A science student who studies history, for example, learns to communicate and reason in new ways. These skills often matter more in a career than narrow expertise alone.",
    s2:"Marcus", s2Post:"In my opinion, students should focus on their chosen field. University is expensive, and required outside courses can delay graduation and add stress. Students who already know their goals would benefit more from advanced study in their major. If people want to explore other subjects, they can easily do so on their own time." },

  { set:11, field:"technology studies", qType:"Alternative", prof:"Dr. Bellini",
    profPost:"Artificial intelligence tools that can write, summarize, and solve problems are now widely available to students. Some instructors believe these tools should be allowed because they reflect how people will work in the future. Others worry that relying on them prevents students from developing essential skills. Do you think students should be allowed to use AI tools to help with their assignments? Why or why not?",
    s1:"Yuki", s1Post:"I think students should be allowed to use AI tools. They are part of modern life, and learning to use them well is an important skill. Used responsibly, they can explain difficult concepts, give quick feedback, and handle routine tasks, letting students focus their energy on deeper thinking and creativity.",
    s2:"Carlos", s2Post:"I disagree. If students depend on AI for their assignments, they may stop learning to write and reason for themselves. The struggle of working through a problem is where real learning happens. I think these tools should be limited in school, so students first build the skills they need to use any tool wisely." },

  { set:12, field:"public policy", qType:"Free-response", prof:"Dr. Andersen",
    profPost:"Several cities are considering making public transportation, such as buses and trains, completely free for all residents. Supporters point to reduced traffic and cleaner air, while others raise concerns about funding and crowding. Rather than simply asking whether it is a good idea, I want to push further. What additional factors should city leaders consider before deciding to make public transportation free?",
    s1:"Sofia", s1Post:"One factor is how the system would be funded. If free transit means higher taxes or less money for maintenance, the quality of service could drop. Cities should study whether lost fare revenue can be replaced without harming the reliability that riders depend on every day.",
    s2:"James", s2Post:"I would add that cities must consider capacity. If buses and trains suddenly become free, ridership could rise sharply, leading to overcrowding and delays. Leaders should also think about whether current routes reach the neighborhoods that need affordable transportation most, not just the busy central areas." }
];
if(typeof module!=='undefined'){module.exports=AD_SETS;}
